services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - sysnetwork

  serverstatisticscollectionservice:
    image: statisticscollector
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - sysnetwork
    environment:
      - SERVERSTATISTICSCONFIG_SERVERIDENTIFIER="win1"
    stdin_open: true
    tty: true

networks:
  sysnetwork:
    driver: bridge
