services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - sysnetwork
  
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - sysnetwork
  
  
  processorandanomalydetector:
    image: processorandanomalydetector
    build:
      context: .
      dockerfile: ProcessorAndAnomalyDetector/Dockerfile
    depends_on:
      - mongo
      - rabbitmq
      - signalreventconsumer
    networks:
      - sysnetwork
    stdin_open: true
    tty: true

  statisticscollector:
    image: statisticscollector
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - sysnetwork
    environment:
      - SERVERSTATISTICSCONFIG_SERVERIDENTIFIER=win1
    stdin_open: true
    tty: true
    
  signalreventconsumer:
    image : signalreventconsumer
    build:
      context: .
      dockerfile: ./SignalREventConsumerService/Dockerfile
    ports:
      - '5124:5124'
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5124
      - ASPNETCORE_URLS=http://+:5124
    networks: 
      - sysnetwork
    stdin_open: true
    tty: true
    
  eventconsumer:
    image: eventconsumer
    build:
      context: .
      dockerfile: ./EventConsumer/Dockerfile
    depends_on:
      - signalreventconsumer
    networks:
      - sysnetwork
    stdin_open: true
    tty: true

networks:
  sysnetwork:
    driver: bridge
       
volumes:
  mongodb: